dataframes:
 data:
  EB:
   input: df_data_EB_test.h5
   output: df_data_EB_test_IdMVA_syst.h5
  EE:
   input: df_data_EE_test.h5
   output: df_data_EE_test_IdMVA_syst.h5
 mc:
  EB:
   input: df_mc_EB_test_clf.h5
   output: df_mc_EB_test_corr_clf_syst_2p5M_spl2.h5
  EE:
   input: df_mc_EE_test_clf.h5
   output: df_mc_EE_test_corr_clf_syst_2p5M_spl2.h5

showerShapes:
 ['probeCovarianceIeIp','probeS4','probeR9','probePhiWidth','probeSigmaIeIe','probeEtaWidth']

chIsos:
 ['probeChIso03','probeChIso03worst']

year:
 2017

workDir:
 /work/threiten/QReg/ReReco17_data/camp_3_1_0/probePS/fullSample

weightsDirs:
 showerShapes:
  weights_qRC_syst_2p5M/spl2
 phoIso:
  weights_qRC_syst_2p5M/spl2
 chIsos:
  weights_qRC_syst_2p5M/spl2

finalWeightsDirs:
  
  
